-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Case"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "caseNumber" text COLLATE pg_catalog."default",
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    "startDate" text COLLATE pg_catalog."default",
    "endDate" text COLLATE pg_catalog."default",
    "lawyerProfileId" text COLLATE pg_catalog."default" NOT NULL,
    "clientId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Case_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CaseNote"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "noteContent" text COLLATE pg_catalog."default",
    "createdDate" text COLLATE pg_catalog."default",
    "caseId" text COLLATE pg_catalog."default" NOT NULL,
    "authorId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CaseNote_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Document"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "documentUrl" text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    "uploadDate" text COLLATE pg_catalog."default",
    "caseId" text COLLATE pg_catalog."default" NOT NULL,
    "uploaderId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Document_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Invoice"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    amount text COLLATE pg_catalog."default",
    "issueDate" text COLLATE pg_catalog."default",
    "dueDate" text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    "caseId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Invoice_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."LawyerProfile"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    "licenseNumber" text COLLATE pg_catalog."default",
    "barAssociation" text COLLATE pg_catalog."default",
    "yearsOfExperience" double precision,
    specialties text COLLATE pg_catalog."default",
    "profilePictureUrl" text COLLATE pg_catalog."default",
    "userId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LawyerProfile_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Message"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    "senderId" text COLLATE pg_catalog."default" NOT NULL,
    "receiverId" text COLLATE pg_catalog."default" NOT NULL,
    "caseId" text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Message_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Organization"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    "pictureUrl" text COLLATE pg_catalog."default" DEFAULT 'https://i.imgur.com/BgkFiid.jpeg'::text,
    "stripeCustomerId" text COLLATE pg_catalog."default",
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Organization_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."OrganizationRole"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" text COLLATE pg_catalog."default" NOT NULL,
    "organizationId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "OrganizationRole_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    "pictureUrl" text COLLATE pg_catalog."default" DEFAULT 'https://i.imgur.com/ZdJSK3Y.jpeg'::text,
    "tokenInvitation" text COLLATE pg_catalog."default",
    "stripeCustomerId" text COLLATE pg_catalog."default",
    status "UserStatus" NOT NULL DEFAULT 'VERIFIED'::"UserStatus",
    "globalRole" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'USER'::text,
    password text COLLATE pg_catalog."default",
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Case"
    ADD CONSTRAINT "Case_clientId_fkey" FOREIGN KEY ("clientId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Case"
    ADD CONSTRAINT "Case_lawyerProfileId_fkey" FOREIGN KEY ("lawyerProfileId")
    REFERENCES public."LawyerProfile" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."CaseNote"
    ADD CONSTRAINT "CaseNote_authorId_fkey" FOREIGN KEY ("authorId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."CaseNote"
    ADD CONSTRAINT "CaseNote_caseId_fkey" FOREIGN KEY ("caseId")
    REFERENCES public."Case" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Document"
    ADD CONSTRAINT "Document_caseId_fkey" FOREIGN KEY ("caseId")
    REFERENCES public."Case" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Document"
    ADD CONSTRAINT "Document_uploaderId_fkey" FOREIGN KEY ("uploaderId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Invoice"
    ADD CONSTRAINT "Invoice_caseId_fkey" FOREIGN KEY ("caseId")
    REFERENCES public."Case" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."LawyerProfile"
    ADD CONSTRAINT "LawyerProfile_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Message"
    ADD CONSTRAINT "Message_caseId_fkey" FOREIGN KEY ("caseId")
    REFERENCES public."Case" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Message"
    ADD CONSTRAINT "Message_receiverId_fkey" FOREIGN KEY ("receiverId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Message"
    ADD CONSTRAINT "Message_senderId_fkey" FOREIGN KEY ("senderId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."OrganizationRole"
    ADD CONSTRAINT "OrganizationRole_organizationId_fkey" FOREIGN KEY ("organizationId")
    REFERENCES public."Organization" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."OrganizationRole"
    ADD CONSTRAINT "OrganizationRole_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;